# Generated by Django 2.1.7 on 2019-03-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190330_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantineregistry',
            name='consumerregistry_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ConsumerRegistry'),
            # models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
            #                      primary_key=True, serialize=False, to='app.ConsumerRegistry')),
            preserve_default=False,
        ),
    ]
