# Generated by Django 2.1.7 on 2019-04-09 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190331_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(blank=True, default='', max_length=50)),
                ('Time', models.DateTimeField(default=datetime.date.today)),
                ('Index', models.IntegerField()),
                ('Data1', models.CharField(blank=True, default='', max_length=20)),
                ('Data2', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UUID_Sheep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(max_length=50, null=True)),
                ('RecordID', models.CharField(max_length=25, null=True)),
                ('PB_Flag', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='processdata',
            name='ReproductionID1',
        ),
        migrations.RemoveField(
            model_name='processdata',
            name='ReproductionID2',
        ),
        migrations.RemoveField(
            model_name='processdata',
            name='ReproductionID3',
        ),
        migrations.RemoveField(
            model_name='processdata',
            name='ReproductionID4',
        ),
        migrations.RemoveField(
            model_name='processdata',
            name='ReproductionID5',
        ),
        migrations.RemoveField(
            model_name='quarantineregistry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='ProductionID',
        ),
        migrations.RemoveField(
            model_name='transportdata',
            name='BatchNum',
        ),
        migrations.AddField(
            model_name='processdata',
            name='Flag',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='processdata',
            name='QRCodeLink',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processdata',
            name='ReproductionID',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processdata',
            name='Step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='Flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarantinedata',
            name='Flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quarantineregistry',
            name='QuarantinePersonID',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarantineregistry',
            name='QuarantinerName',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selldata',
            name='Flag',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='selldata',
            name='SellID',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transportdata',
            name='Transport_Flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transporterregistry',
            name='Flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumerregistry',
            name='RegisterTimeConsumer',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='ProcessID',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='ProductionID',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='processorregistry',
            name='IDNo',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='quarantinedata',
            name='ProductionId',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='selldata',
            name='ConsumerID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sellerregistry',
            name='RegisterTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transportdata',
            name='Flag',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='transportdata',
            name='ProductionID',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='transportdata',
            name='TransactionEndTime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transportdata',
            name='TransactionStartTime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='basestationdata',
            name='Sheep_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProductionData'),
        ),
    ]
