# Generated by Django 2.1.7 on 2019-04-11 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190331_1424'),
    ]

    operations = [



















        migrations.AlterField(
            model_name='consumerregistry',
            name='RegisterTimeConsumer',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='ProcessID',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='ProcessTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 2, 30, 37, 667300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='ProductionID',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='processorregistry',
            name='IDNo',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='quarantinedata',
            name='ProductionId',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='quarantinedata',
            name='QuarantineTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 2, 30, 37, 667300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selldata',
            name='ConsumerID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='selldata',
            name='ProductionID',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='selldata',
            name='SPReceiveTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 2, 30, 37, 668300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sellerregistry',
            name='RegisterTime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transportdata',
            name='Flag',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='transportdata',
            name='ProductionID',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='transportdata',
            name='TransactionEndTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 2, 30, 37, 668300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transportdata',
            name='TransactionStartTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 2, 30, 37, 668300, tzinfo=utc)),
        ),
    ]
