# Generated by Django 2.1.7 on 2019-04-11 02:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190411_1034'),
    ]

    operations = [



        migrations.AlterField(
            model_name='transportdata',
            name='TransactionEndTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 2, 56, 6, 995772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transportdata',
            name='TransactionStartTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 2, 56, 6, 995772, tzinfo=utc)),
        ),
    ]
