# Generated by Django 2.1.7 on 2019-04-12 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190411_1057'),
    ]

    operations = [

        migrations.CreateModel(
            name='sheep_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordID', models.CharField(max_length=25, null=True)),
                ('qr_code', models.CharField(max_length=88, null=True)),
            ],
        ),

    ]
